markdown: kramdown
highlighter: rouge
url: http://alenzhai.github.io/
repository: https://github.com/AlenZhai
defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "blogs_item"


collections:
  posts:
    permalink: /blogs/:year/:month/:day/:title/
    output: true
  tutorials:
    output: true

name: Jekyll • Simple, blog-aware, static sites
description: Transform your plain text into static websites and blogs

twitter:
  username: jekyllrb

logo: /img/logo-2x.png

gems:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

exclude:
  - .gitignore
  - README.md