markdown: kramdown
highlighter: rouge
url: http://alenzhai.github.io/
repository: https://github.com/AlenZhai

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "blogs_item"


collections:
  posts:
    permalink: /blogs/:year/:month/:day/:title/
    output: true
  tutorials:
    output: true

name: 苦海行舟●个人空间

gems:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

exclude:
  - .gitignore
  - README.md